### ISSUE TITLE
Fatal error: Hook 'database_connected' does not exist 

### ISSUE THREAD

**Issue by drmuey** [bigpresh/Dancer-Plugin-Database#62]
Details at https://rt.cpan.org/Ticket/Display.html?id=103427

w/ a possible fix at

https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny/issues/4

**Comment by ambs** [comment]
This is a known problem. It can be fixed (well, workaround) importing Dancer2::Plugin::Database as the final Dancer2 plugin (well, at least if worked that way everytime we need).

The possible fix seems not to be correct, unfortunately. But we are working on this.

Cheers
ambs

**Comment by ambs** [comment]
Dear @drmuey, can you please check if this PR helps in your problems?
https://github.com/PerlDancer/Dancer2/pull/889

Thanks

**Comment by ambs** [comment]
Solved in Dancer2. Should be working with recent version. Please reopen if not.
