### ISSUE TITLE
Malformed SQL for update queries

### ISSUE THREAD

**Issue by nunorc** [bigpresh/Dancer-Plugin-Database#64]
It seems that it is possible to create a wrong SQL statement for an update with the current code version. Here is a simple snippet of a Dancer application:

    get '/update' => sub {
      my $update = { user=>'user', username=>'username' };
      print STDERR "Update:\n", Dumper($update);

      for (1..3) {
        print STDERR "Iter $_:\n";
        my $row = database->quick_select('users', {id=>2});
        database->quick_update('users', {id=>2}, $update);

        print STDERR Dumper($row);
      }
    };

The current code as a `sort` applied to the list of keys in the data structure with the update values (here https://github.com/bigpresh/Dancer-Plugin-Database/blob/master/Shared/lib/Dancer/Plugin/Database/Core/Handle.pm#L355), but there is no sort when the values are copied to the binding parameters array. This leads to sometimes the list of binding names with a different order for the binding values. A possible example of the execution of the above code is:

    Update:
    $VAR1 = {
              'user' => 'user',
              'username' => 'username'
            };
    Iter 1:
    $VAR1 = {
              'user' => 'username',
              'username' => 'user',
              'id' => 2
            };
    Iter 2:
    $VAR1 = {
              'id' => 2,
              'user' => 'user',
              'username' => 'username'
            };
    Iter 3:
    $VAR1 = {
              'id' => 2,
              'username' => 'username',
              'user' => 'user'
            };

In the first iteration the values where using a different order, which lead to a wrong update. Pull request https://github.com/bigpresh/Dancer-Plugin-Database/pull/63 is a possible fix that helps to illustrate the problem. Thank you for your time, and I hope I'm not missing anything.

**Comment by nunorc** [comment]
Here is a 2nd better example:

    get '/update' => sub {
      my $update = { user=>'user', username=>'username' };
      print STDERR 'UPDATE: ',join(',', map { $_.'='.$update->{$_} } sort keys %$update), "\n";
      database->quick_update('users', {id=>2}, $update);
      my $row = database->quick_select('users', {id=>2});
      print STDERR "SELECT: ", join(', ', map { $_.'='.$row->{$_} } sort keys %$row), "\n\n";
    };

After some calls to /update:

    UPDATE: user=user,username=username
    SELECT: id=2, user=user, username=username
    UPDATE: user=user,username=username
    SELECT: id=2, user=username, username=user
    UPDATE: user=user,username=username
    SELECT: id=2, user=user, username=username

**Comment by ambs** [comment]
Fixed in 0.09 (Dancer::Plugin::Database::Core). Thanks.

**Comment by nunorc** [comment]
Just to correct, this was fixed in version 0.10. Thank you
