### ISSUE TITLE
Dancer::Plugin::Database::Core::Handle quick_update updates wrong fields

### ISSUE THREAD

**Issue by sime-k** [bigpresh/Dancer-Plugin-Database#67]
While using "quick_update" in version 0.09 the values get really messed up. 
In line 361 keys of given hash are sorted and values are left as is.

**Comment by nunorc** [comment]
This problem is also reported in issue https://github.com/bigpresh/Dancer-Plugin-Database/issues/64

**Comment by ambs** [comment]
Fixed in Dancer::Plugin::Database::Core 0.09. Thanks

**Comment by nunorc** [comment]
Correction, this was fixed in version 0.10. Thank you
