### ISSUE TITLE
log_queries seems broken in dancer2

### ISSUE THREAD

**Issue by djzort** [bigpresh/Dancer-Plugin-Database#70]
I get this error when log_queries: 1 is on in the config file:

Undefined subroutine &Dancer::Logger::debug called at /home/dean/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Dancer/Plugin/Database/Core/Handle.pm line 285.

**Comment by ambs** [comment]
Fixed in Dancer::Plugin::Database::Core v0.12
Thanks
