### ISSUE TITLE
Fails since 2016-08-06

### ISSUE THREAD

**Issue by andk** [bigpresh/Dancer-Plugin-Database#89]
As per subject. Sample fail reports:

http://www.cpantesters.org/cpan/report/71998522 2016-08-07T19:14:00
http://www.cpantesters.org/cpan/report/71942118 2016-08-06T05:14:22

While we are at it, it also seems there is a minimum perl version required, maybe 5.8.9, as a glance at the matrix suggests:

http://matrix.cpantesters.org/?dist=Dancer-Plugin-Database-2.12

If this is intentional, it would be cool if you could declare your requirement. That way the intentional FAILS are converted to UNKNOWNS and it makes other problems stand out better. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH&&Thanks,

**Comment by bigpresh** [comment]
Hmm.  Yes, something's wrong.

I can confirm that on my local machine, D::P::Database (the Dancer1 version) works with D::P::D::Core 0.14, but fails with the recent D::P::D::Core 0.15, so something in the recent refactor in 0.15 has caused breakage.  (Despite D::P::D::Core's tests all still passing - so it seems the tests aren't good enough!)

Will look in to this ASAP.

At a quick skim over the changes in D::P::D::Core 0.15, I see no obvious culprit, but something is clearly wrong!

**Comment by bigpresh** [comment]
OK, in some cases the SQL query is not being generated properly since the refactor.

It seems to be tests which supply specific column names to fetch.  Some failing test output, with the queries that were executed, follow - note the lack of the query in the failing ones (the SQL query should appear after "SELECT query" - e.g.  `Executing SELECT query ... with params ...` - the dots show where the query and any bind params should be:

```
[7362] debug @0.000489> [hit #29]Executing DELETE query DELETE FROM "users"  WHERE "id"=? with params 42 in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
ok 29 - quick_delete returned OK status
ok 30 - quick_delete deleted a record successfully
[7362] debug @0.000722> [hit #31]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 31 - Fetched a single specified column OK

#   Failed test 'Fetched a single specified column OK'
#   at t/01-basic.t line 118.
#                   ''
#     doesn't match '(?^m:^bigpresh$)'
[7362] debug @0.000623> [hit #32]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 32 - Fetched multiple specified columns OK

#   Failed test 'Fetched multiple specified columns OK'
#   at t/01-basic.t line 122.
#                   ''
#     doesn't match '(?^m:^bigpresh:admin$)'
[7362] debug @0.000589> [hit #33]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 33 - User-specified LIMIT works (1 row)

#   Failed test 'User-specified LIMIT works (1 row)'
#   at t/01-basic.t line 127.
#          got: '0'
#     expected: '1'
[7362] debug @0.000590> [hit #34]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 34 - User-specified LIMIT works (2 row)

#   Failed test 'User-specified LIMIT works (2 row)'
#   at t/01-basic.t line 130.
#          got: '0'
#     expected: '2'
[7362] debug @0.000546> [hit #35]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 35 - Records sorted properly

#   Failed test 'Records sorted properly'
#   at t/01-basic.t line 135.
#          got: ''
#     expected: 'bigpresh:bodger:mousey:mystery1:mystery2:sukria'
[7362] debug @0.000572> [hit #36]Executing SELECT query  with params  in /usr/local/share/perl/5.20.2/Dancer/Plugin/Database.pm l. 28
not ok 36 - Records sorted properly in descending order

#   Failed test 'Records sorted properly in descending order'
#   at t/01-basic.t line 138.
#          got: ''
#     expected: 'sukria:mystery2:mystery1:mousey:bodger:bigpresh'
```

**Comment by bigpresh** [comment]
I see the problem.  Should get a fixed Dancer::Plugin::Database::Core out shortly.

**Comment by bigpresh** [comment]
Right, Dancer::Plugin::Database::Core 0.16 with the fix is on its way to CPAN now.

I'll get a new release of Dancer::Plugin::Database and Dancer2::Plugin::Database out which demand that version shortly, too.

**Comment by bigpresh** [comment]
Right new versions of the D1 & D2 plugins which require core 0.16 are on their way to CPAN now.

Thanks for the heads up on this, I'd not seen the cpantesters reports yet!
